### ISSUE TITLE
Getting the native model for compatibility with shap.TreeExplainer

### ISSUE THREAD

**Issue by nicolasaldecoa** [erdogant/hgboost#10]
Hello, first of all really nice project. I've just found out about it today and started playing with it a little bit.
Is there any way to get the trained model as an XGBoost, LightGBM or CatBoost class in order to fit a [shap.TreeExplainer](https://shap-lrjball.readthedocs.io/en/docs_update/generated/shap.TreeExplainer.html) instance to it? 

Thanks in advance!
-Nicolás

**Comment by nicolasaldecoa** [comment]
Nevermind! I checked the code and it is stored under the attribute "model".

**Comment by erdogant** [comment]
great!
