### ISSUE TITLE
Treeplot failure - missing graphviz dependency

### ISSUE THREAD

**Issue by ninjit** [erdogant/hgboost#12]
I'm running through the example classification notebook now, and the treeplot fails to render, with the following warning:

![Screen Shot 2022-10-04 at 14 30 21](https://user-images.githubusercontent.com/753263/193935047-36e0a924-fa0b-4acf-91ed-081bf734eedb.png)

It seems that graphviz being a compiled c library is not bundled in pip (it is included in conda install treeplot/graphviz though).

Since we have no recourse to add this to pip requirements, maybe a sentence in the Instalation instructions warning that graphviz must already be available and/or installed separately.

(note the suggested apt command for linux is not entirely necessary, because pydot does get installed with treeplot via pip)

**Comment by erdogant** [comment]
Good point. I added this to the installation instructions on the [documentation pages](https://erdogant.github.io/hgboost/pages/html/Installation.html#installation). However, do you now receive this message and you can still make the tree plot?

**Comment by ninjit** [comment]
`sudo apt install graphviz` was enough in my situation, but for other OSes there maybe other hoops to jump through.
e.g. on mac `brew instal graphiz`, on windows... I have no idea.

`conda install graphiz` maybe the universal solution, since they bundle the require C libraries/binaries, but I've had a lot of issues in the past mixing conda and pip installs within the same environment.
