### ISSUE TITLE
hgb.plot command returns seaborn regplot error

### ISSUE THREAD

**Issue by ninjit** [erdogant/hgboost#13]
From the example classification notebook:
![Screen Shot 2022-10-04 at 14 42 22](https://user-images.githubusercontent.com/753263/193936490-6d10165e-996c-447f-8ca7-a693072ad903.png)

Maybe tmpdf is a list or dictionary that seaborn is complaining about?

**Comment by erdogant** [comment]
Found it and fixed it! The order of the input parameters were changed for regplot so no now I explicitly define them.
Update with:

`pip install -U hgboost
`

Version should be >= 1.1.3

**Comment by ninjit** [comment]
Confirmed, thanks!

It also fixed some of the blank plots I was getting through
`hgb.plot_params`
There was no associated error message there, so I wasn't sure what was missing, but I now see scatter plots of each hyperparameter vs iteration #
