### ISSUE TITLE
Problem with XGB Classifier..in early stopping rounds

### ISSUE THREAD

**Issue by chandrabhuma** [erdogant/hgboost#21]
[XGBClassifier.fit() got an unexpected keyword argument 'early_stopping_rounds'](https://stackoverflow.com/questions/78713048/xgbclassifier-fit-got-an-unexpected-keyword-argument-early-stopping-rounds)
This problem is coming even with hgboost.ensemble. Could you pl check this problem. Even after updating !pip install -U hgboost, there is no use

**Comment by erdogant** [comment]
Thank you for mentioning this. I created a fix for it. The early_stopping_rounds parameter was moved from the fit towards the initialization in xgboost. 

Update to the latest version with
`pip install -U hgboost
`

**Comment by chandrabhuma** [comment]
It is working now. Thanks for the prompt response
