### ISSUE TITLE
Error in rmse calculaiton

### ISSUE THREAD

**Issue by SSLPP** [erdogant/hgboost#3]
```
if self.eval_metric=='rmse':
                loss = mean_squared_error(y_test, y_pred)
```
mean_squared_error in sklearn gives mse, use `mean_squared_error(y_true, y_pred, squared=False)` for rmse

**Comment by erdogant** [comment]
Thank you for mentioning this point.
I fixed the mse and rmse usage and released a new version.

Update with:

`pip install -U hgboost`

Check the version, should be >= 0.1.7

```
import hgboost
print(hgboost.__version__)

```
