### ISSUE TITLE
Specific data results problem

### ISSUE THREAD

**Issue by recherHE** [erdogant/hgboost#5]
Your package is very convenient and effective, but if I want to redraw the plot, what can I do to get specific data results?
thanks for helping.

**Comment by erdogant** [comment]
Great! Can you elaborate a bit more about "specific"?

All the results are stored in the results dict:

```
hgb.results.keys()
# dict_keys(['params', 'summary', 'trials', 'model', 'val_results', 'comparison_results'])

# All the validation results can then be found with:
hgb.results['val_results'].keys()
# dict_keys(['class_names', 'pos_label', 'neg_label', 'y_true', 'y_pred', 'y_proba', 'auc', 'f1', 'kappa', 'report', 'thresholds', 'fpr', 'tpr', 'average_precision', 'precision', 'recall', 'MCC', 'CAP', 'TPFP', 'confmat', 'threshold'])

```

**Comment by recherHE** [comment]
thanks a lot! these will help me out.&nbsp;

---Original---
From: "Erdogan ***@***.***&gt;
Date: Thu, Mar 18, 2021 22:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [erdogant/hgboost] Specific data results problem (#5)




 
Great! Can you elaborate a bit more about "specific"?
 
All the results are stored in
 hgb.results.keys() # dict_keys(['params', 'summary', 'trials', 'model', 'val_results', 'comparison_results']) # All the validation results can then be found with: hgb.results['val_results'].keys() # dict_keys(['class_names', 'pos_label', 'neg_label', 'y_true', 'y_pred', 'y_proba', 'auc', 'f1', 'kappa', 'report', 'thresholds', 'fpr', 'tpr', 'average_precision', 'precision', 'recall', 'MCC', 'CAP', 'TPFP', 'confmat', 'threshold'])
