### ISSUE TITLE
issue with shuffling results and loading model  

### ISSUE THREAD

**Issue by chennavc** [erdogant/hgboost#8]
1.  R2, RMSE,MAE, MAPE  results were changing. so it is difficult to compare different experiments. 
2. I am unable to load the saved model.

**Comment by erdogant** [comment]
Can you show both issues with an example?

**Comment by erdogant** [comment]
During initialization, you can set the random_state. Have you tried that already?

```
from hgboost import hgboost
hg = hgboost(random_state=0)
results = hg.xgboost(X, y)

```

**Comment by erdogant** [comment]
Reopen this issue and let me know if you had something else in mind.
